-- 1. สร้างตาราง History
CREATE TABLE PLC_STATUS_HISTORY (
  ID            NUMBER         GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  MACHINE_ID    VARCHAR2(64)   NOT NULL,
  MACHINE_NAME  VARCHAR2(128),
  MACHINE_MODE  VARCHAR2(32),
  STATUS        VARCHAR2(32)   NOT NULL,
  PREV_STATUS   VARCHAR2(32),
  LOT_ID        VARCHAR2(64),
  JOB_NAME      VARCHAR2(128),
  ALARM_TEXT    VARCHAR2(512),
  ERROR_DETAIL  VARCHAR2(2000),
  OCCURRED_AT   TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL
);

-- 2. Index
CREATE INDEX IDX_PLC_HISTORY_MACHINE ON PLC_STATUS_HISTORY(MACHINE_ID, OCCURRED_AT DESC);
CREATE INDEX IDX_PLC_HISTORY_TIME    ON PLC_STATUS_HISTORY(OCCURRED_AT DESC);

-- 3. GRANT SELECT 4 EAP tables (รันด้วย DBA / schema owner)
-- แก้ 'INTELLIGENT_READ_PA01_PRD' เป็น user ที่ backend ใช้
GRANT SELECT ON PAEAPTRACE.EAP_EQP_EVENT_PNL_PNL TO INTELLIGENT_READ_PA01_PRD;
GRANT SELECT ON PAEAPTRACE.EAP_EQP_ALM          TO INTELLIGENT_READ_PA01_PRD;
GRANT SELECT ON PAEAPTRACE.EAP_GUI_ERR_MSG      TO INTELLIGENT_READ_PA01_PRD;
GRANT SELECT ON DWD_PA01_PRD.LOTINFO_MAIN       TO INTELLIGENT_READ_PA01_PRD;

-- 4. GRANT INSERT ลงตาราง History (ใช้ user เดียวกันที่สร้าง table)
-- ถ้าสร้าง table ด้วย user อื่น รัน:
-- GRANT INSERT ON PLC_STATUS_HISTORY TO INTELLIGENT_READ_PA01_PRD;

-- 5. Retention — ลบข้อมูลเก่า 90 วัน (รันด้วย DBA หรือ user ที่มีสิทธิ์)
BEGIN
  DBMS_SCHEDULER.CREATE_JOB(
    job_name        => 'PLC_HISTORY_PURGE',
    job_type        => 'PLSQL_BLOCK',
    job_action      => 'BEGIN DELETE FROM PLC_STATUS_HISTORY WHERE OCCURRED_AT < SYSTIMESTAMP - 90; COMMIT; END;',
    start_date      => SYSTIMESTAMP,
    repeat_interval => 'FREQ=DAILY; BYHOUR=02; BYMINUTE=00; BYSECOND=00',
    enabled         => TRUE,
    comments        => 'Purge PLC_STATUS_HISTORY older than 90 days'
  );
END;
/