WITH panel_stats AS (
  SELECT
    COALESCE(SUB_EQP_ID, MAIN_EQP_ID) AS MACHINE_ID,
    LOT_ID,
    COUNT(DISTINCT CASE WHEN PANEL_ID NOT LIKE 'Error\_%' ESCAPE '\' THEN PANEL_ID END) AS OK_PANELS,
    SUM(CASE WHEN PANEL_ID LIKE 'Error\_%' ESCAPE '\' THEN 1 ELSE 0 END) AS ERROR_COUNT
  FROM PAEAPTRACE.EAP_EQP_EVENT_PNL_PNL
  WHERE DATE_TIME >= SYSDATE - 30/1440
  GROUP BY COALESCE(SUB_EQP_ID, MAIN_EQP_ID), LOT_ID  -- ★ เพิ่มเครื่อง
)
SELECT
  COALESCE(E.SUB_EQP_ID, E.MAIN_EQP_ID) AS MACHINE_ID,
  E.MAIN_EQP_NAME,
  E.DATE_TIME     AS EVENT_TIME,
  E.PRODUCTMODE   AS MACHINE_MODE,
  E.EQPSTATUS     AS MACHINE_STATUS,
  E.LOT_ID,
  E.PANEL_ID      AS LAST_PANEL_ID,
  E.DATE_TIME     AS PANEL_TIME,
  P.OK_PANELS     AS TOTAL_SHEET,
  P.ERROR_COUNT   AS ERROR_SHEET,
  CASE
    WHEN (P.OK_PANELS + P.ERROR_COUNT) = 0 OR P.OK_PANELS IS NULL THEN 0
    ELSE ROUND(P.OK_PANELS * 100.0 / (P.OK_PANELS + P.ERROR_COUNT), 2)
  END AS PCT_QR,
  A.ALARM_TEXT,
  A.ALARM_CATEGORY,
  G.ERROR_DETAIL,
  T.PN AS PRODUCT_ID
FROM PAEAPTRACE.EAP_EQP_EVENT_PNL_PNL E
LEFT JOIN panel_stats P 
  ON P.LOT_ID = E.LOT_ID 
  AND P.MACHINE_ID = COALESCE(E.SUB_EQP_ID, E.MAIN_EQP_ID)
LEFT JOIN (
  SELECT MAIN_EQP_ID, SUB_EQP_ID, ALARM_TEXT, ALARM_CATEGORY,
         ROW_NUMBER() OVER (PARTITION BY MAIN_EQP_ID, SUB_EQP_ID ORDER BY DATE_TIME DESC) AS rn
  FROM PAEAPTRACE.EAP_EQP_ALM
  WHERE DATE_TIME >= SYSDATE - 30/1440
) A ON A.MAIN_EQP_ID = E.MAIN_EQP_ID 
   AND COALESCE(A.SUB_EQP_ID, A.MAIN_EQP_ID) = COALESCE(E.SUB_EQP_ID, E.MAIN_EQP_ID)  -- ★ JOIN SUB_EQP_ID
   AND A.rn = 1
LEFT JOIN (
  SELECT MAIN_EQP_ID, SUB_EQP_ID, ERROR_DETAIL,
         ROW_NUMBER() OVER (PARTITION BY MAIN_EQP_ID, SUB_EQP_ID ORDER BY DATE_TIME DESC) AS rn
  FROM PAEAPTRACE.EAP_GUI_ERR_MSG
  WHERE DATE_TIME >= SYSDATE - 30/1440
) G ON G.MAIN_EQP_ID = E.MAIN_EQP_ID 
   AND COALESCE(G.SUB_EQP_ID, G.MAIN_EQP_ID) = COALESCE(E.SUB_EQP_ID, E.MAIN_EQP_ID)
   AND G.rn = 1
LEFT JOIN (
  SELECT MAIN_EQP_ID, SUB_EQP_ID, PN,
         ROW_NUMBER() OVER (PARTITION BY MAIN_EQP_ID, SUB_EQP_ID ORDER BY DATE_TIME DESC) AS rn
  FROM PAEAPTRACE.EAP_EQP_TRACE
  WHERE DATE_TIME >= SYSDATE - 30/1440
    AND PN IS NOT NULL
) T ON T.MAIN_EQP_ID = E.MAIN_EQP_ID 
   AND COALESCE(T.SUB_EQP_ID, T.MAIN_EQP_ID) = COALESCE(E.SUB_EQP_ID, E.MAIN_EQP_ID)
   AND T.rn = 1
LEFT JOIN DWD_PA01_PRD.LOTINFO_MAIN M
  ON M.LOT_NAME = E.LOT_ID
WHERE E.DATE_TIME >= SYSDATE - 30/1440
ORDER BY E.DATE_TIME DESC